[package]
name = "rust-heightmap"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.24.0"
nalgebra = "0.34.1"
tokio = { version = "1.48.0", features = ["rt"] }
parrot-rng = "0.7.1"
bevy = "0.17.3"
