[package]
name = "rust-heightmap"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { git = "https://github.com/Lokathor/bytemuck" }
glam = { git = "https://github.com/bitshifter/glam-rs" }
nalgebra = { git = "https://github.com/dimforge/nalgebra" }
tokio = { version = "1.48.0", features = ["rt"] }
parrot-rng = "0.7.1"
bevy = "0.17.3"
rand = "0.9.2"
